# Generated by Django 5.1 on 2024-08-20 19:05

import base.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('refMessage', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dateMessage', models.DateField()),
                ('objet', models.CharField(max_length=100)),
                ('fichierPDFMessage', models.FileField(upload_to=base.models.message_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('cin', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChoixTerrain',
            fields=[
                ('choixID', models.AutoField(primary_key=True, serialize=False)),
                ('geo', models.CharField(default='', max_length=100)),
                ('map', models.ImageField(blank=True, null=True, upload_to=base.models.choix_terrain_upload_path)),
                ('secteur', models.CharField(max_length=100)),
                ('surface', models.FloatField()),
                ('commune', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('quartier', models.CharField(blank=True, max_length=100, null=True)),
                ('dateChoix', models.DateField()),
                ('PV', models.FileField(upload_to=base.models.choix_terrain_upload_path)),
                ('extrait_PA', models.FileField(upload_to=base.models.choix_terrain_upload_path)),
                ('extrait_CarteRisques', models.FileField(upload_to=base.models.choix_terrain_upload_path)),
                ('refFonciere', models.CharField(max_length=100)),
                ('refMessage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.message')),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id_commission', models.AutoField(primary_key=True, serialize=False)),
                ('choixTerrains', models.ManyToManyField(to='base.choixterrain')),
                ('refMessage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.message')),
                ('participants', models.ManyToManyField(to='base.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('rapportID', models.AutoField(primary_key=True, serialize=False)),
                ('nomRapport', models.CharField(max_length=100)),
                ('dateRapport', models.DateField()),
                ('emplacementRapport', models.CharField(max_length=255)),
                ('choixTerrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.choixterrain')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsableAgence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChefImmediat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.responsableagence')),
            ],
        ),
    ]
