# Generated by Django 5.1 on 2024-08-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choixterrain',
            name='map',
        ),
        migrations.AlterField(
            model_name='choixterrain',
            name='geo',
            field=models.JSONField(default=list),
        ),
    ]
