# Generated by Django 5.1 on 2024-08-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_choixterrain_map_alter_choixterrain_geo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choixterrain',
            name='geo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
